# Generated by Django 3.0 on 2019-12-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name_plural': '知识库'},
        ),
        migrations.AddField(
            model_name='base',
            name='cdate',
            field=models.DateTimeField(default='2019-12-31', verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='base',
            name='command',
            field=models.TextField(blank=True, max_length=500, verbose_name='命令'),
        ),
        migrations.AddField(
            model_name='base',
            name='label',
            field=models.CharField(blank=True, max_length=20, verbose_name='标签'),
        ),
    ]
