# Generated by Django 3.0 on 2019-12-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20191231_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='command',
            new_name='mingling',
        ),
    ]
