# Generated by Django 3.0 on 2019-12-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TODOLIST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('cdate', models.DateField(verbose_name='创建时间')),
                ('description', models.CharField(blank=True, max_length=20, null=True, verbose_name='描述')),
                ('状态', models.CharField(blank=True, choices=[('Y', '是'), ('N', '否')], max_length=1, null=True, verbose_name='是否完成')),
                ('date2', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('内容', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '待办事项',
            },
        ),
    ]
